## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [5]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.47639088 0.92642035 0.90415579 0.75743364 0.44208931 0.59535945
 0.58209316 0.07078115 0.         0.48795788]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [6]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [9]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 3 2]
 [1 0 4]
 [1 0 1]
 [4 3 1]
 [1 2 1]
 [4 3 2]
 [1 2 1]
 [1 1 1]
 [1 1 2]
 [4 1 0]]
[[0 3 2]
 [1 0 4]
 [1 0 1]
 [4 3 1]
 [1 2 1]
 [4 3 2]
 [1 2 1]
 [1 1 2]
 [4 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [30]:
a = [[1, 0, 1, 0, 0, 1],
     [1, 1, 1, 0, 0, 1],
     [1, 0, 1, 0, 0, 1],
     [1, 0, 1, 0, 1, 1],
     [1, 0, 1, 0, 0, 1]]
b = np.array(a)
u, idx = np.unique(b, axis=0, return_index=True)
res = u[idx.argsort()]
print(res)

[[1 0 1 0 0 1]
 [1 1 1 0 0 1]
 [1 0 1 0 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [48]:
def notnull_numpy(x):
    y=np.prod(np.diag(x)[np.diag(x)!=0])
    return y
z=np.array([[1,0,1],[2,0,2],[3,0,3],[4,4,4]])
def notnull_python(arr):
    s=1
    for i in range(len(arr)): 
        for j in range(len(arr[0])): 
            if i==j and arr[i][j]!=0:
                        s*=arr[i][j]
    return s
arr1=[[1, 0, 1], [2, 0, 2], [3, 0, 3],[4, 4, 4]] 
print("numpy", notnull_numpy(z))
print("python", notnull_python(arr1))


numpy 3
python 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [25]:
def multisets_python(A,B):
    x=set(A)
    y=set(B)
    if x==y:
        return True
    return False
a = [1, 2, 2, 4]
b = [4, 2, 1, 2]
print('Python',multisets_python(a,b))
def multisets_numpy(A,B):
    if (A.size != B.size):
        return False
    res=np.allclose (A, B, atol= A.size-1 )
    return res
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print('Numpy', multisets_numpy(x,y))

Python True
Numpy True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [5]:
def max_element_numpy(x):
   zero=x==0
   return x[1:][zero[:-1]].max()
f = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print("Numpy",max_element(f))
def max_element_python(x):
    maxy=max(y[i] for i in range(1, len(y)) if not y[i-1])
    return maxy
y=[6, 2, 0, 3, 0, 0, 5, 7, 0]
print('Python', max_element_python(y))

Numpy 5
Python 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [35]:
def run_length_encoding_vect(x):
    y = np.hstack((np.ones(1), x[:- 1]))
    first_positions = x != y
    first_positions[0] = True
    indexes_1 = np.arange(np.size(x))[first_positions]
    indexes_2 = np.hstack((indexes_1[1:], np.array([np.size(x)])))
    return x[first_positions], indexes_2 - indexes_1
f=np.array([2, 2, 2, 3, 3, 3, 5])
print('Numpy',run_length_encoding_vect(f))
def run_length_encoding_non_vect(x):
    val_list = [x[0]]
    num_list = list()
    counter = 1
    for i in range(1, len(x)):
        if(x[i - 1] == x[i]):
            counter = counter + 1
        else:
            val_list.append(x[i])
            num_list.append(counter)
            counter = 1
    num_list.append(counter)
    return (val_list, num_list)
h=[2, 2, 2, 3, 3, 3, 5]
print('python', run_length_encoding_non_vect(h))


Numpy (array([2, 3, 5]), array([3, 3, 1]))
python ([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [53]:
import math
def evklid_numpy(X, Y):
    return np.sqrt(np.sum((X[:, np.newaxis] - Y) ** 2, axis=-1))
x = np.array([[1, 2], [2, 4]])
y = np.array([[4, 2], [1, 2]])
print('Numpy', evklid_numpy(x,y))
def evklid_python(X, Y):
    result_matr = list()
    for i in range(len(X)):
        curr_list = list()
        for j in range(len(Y)):
            dist = 0
            for k in range(len(X[0])):
                dist += (X[i][k] - Y[j][k]) ** 2
            curr_list.append(math.sqrt(dist))
        result_matr.append(curr_list)
    return result_matr
a = [[1, 2], [2, 4]]
b = [[4, 2], [1, 2]]
print('Python', evklid_python(a,b))

Numpy [[3.         0.        ]
 [2.82842712 2.23606798]]
Python [[3.0, 0.0], [2.8284271247461903, 2.23606797749979]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [58]:
calorie_stats=np.array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [62]:
average_calories=np.mean(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [64]:
calorie_stats_sorted=np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [65]:
median_calories=np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [77]:
nth_percentile=np.percentile(calorie_stats,3.3)
print(nth_percentile)

60.16


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [81]:
kolvo=np.sum(calorie_stats>60)
more_calories=kolvo/calorie_stats.size
print(more_calories*100)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [82]:
calorie_std=np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Информация о том, что у большинства компаний колораж выше может помочь маркетингу компании. 
Как показывают данные, у 96 процентов компаний затрачивается больше колорий на порцию. Более того, среднее значение, медиана
и невысокое значение стандартного отклонения подтверждают это.
